"""Initial migration.

Revision ID: 6b2528703a44
Revises: 
Create Date: 2026-04-17 10:40:20.810652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b2528703a44'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loyalty', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loyalty', schema=None) as batch_op:
        batch_op.drop_column('level')

    # ### end Alembic commands ###
